<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('APPS:admin.library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	private $file = 'EXT:webim.conf.conf';
	private $default = array();
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		$this->file = Wind::getRealPath($this->file, false);
	}
	
	/* (non-PHPdoc)
	 * @see WindController::run()
	 */
	public function run() {
		$conf = @include $this->file;
		$conf || $conf = $this->default;
		$this->setOutput($conf, 'conf');
	}
	
	/**
	 * 应用的设置提交
	 *
	 */
	public function doRunAction() {
		$conf = $this->getInput('conf', 'post');
		WindFile::savePhpData($this->file, $conf);
		$this->showMessage('success');
	}
}

?>
